- name: ec2 launcher
  hosts: localhost
  gather_facts: yes
  connection: local
  tasks:
  - name: launching ec2 instance
    ec2:
      instance_type: t2.micro
      key_name: sankar-devops
      image: ami-06b710d39da76565d
      region: us-east-2
      group: default
      count: 1
      wait: yes
      wait_timeout: 180
      assign_public_ip: yes
      vpc_subnet_id: subnet-eb3cd196
    register: ec2  
  - name: Add ip to inventory 
    add_host: 
        hostname: "{{ item.public_ip }}"
        groupname: tag_Name_NginxDemo
        ansible_user: jenkins
        ansible_become: yes
    with_items: "{{ ec2.instances }}"
