- name: ec2 launcher
  hosts: localhost
  gather_facts: yes
  connection: local
  tasks:
  - name: Get Info Block
    block: 
      - name: Get Running instance Info
        ec2_instance_info:
        register: ec2info 
      - name: Print info
        debug: var="ec2info.instances"
  - name: launching ec2 instance
    ec2:
      instance_type: t2.micro
      key_name: sankar-devops
      image: ami-06b710d39da76565d
      region: us-east-2
      group: All-Traffic
      count: 1
      wait: yes
      wait_timeout: 500
      assign_public_ip: yes
      vpc_subnet_id: subnet-eb3cd196
    register: ec2  
  - name: Add ip to inventory 
    add_host: 
        hostname: "{{ item.public_ip }}"
        groupname: tomcat
        ansible_user: jenkins
        ansible_become: yes
    loop: "{{ ec2.instances }}"
- name: tomcat setup
  hosts: tomcat
  become: true
  tasks:
  - name: Install Java
    command: yum install java-1.8.0-openjdk -y
    command: yum install java-1.8.0-openjdk-devel -y
  - lineinfile:
     path: /etc/profile
     line: 'export JRE_HOME=/usr/lib/jvm/jre'
  - lineinfile:
     path: /etc/profile
     line: 'export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk'
  - name: ensure a list of packages installed
    yum:
     name: "{{ packages }}"
    vars:
     packages:
      - tomcat
      - tomcat-webapps
      - tomcat-admin-webapps
      - tomcat-docs-webapp
      - tomcat-javadoc
     state: present
  - name: Copy fil
    copy:
     src: /var/lib/jenkins/tomcat-users.xml
     dest: /usr/share/tomcat/conf/tomcat-users.xml
  - name: enable service tomcat
    systemd:
     name: tomcat
     enabled: yes
  - name: start service tomcat
    systemd:
     name: tomcat
     state: started
