- name: ec2 launcher
  hosts: localhost
  gather_facts: yes
  become: False
  connection: local
  tasks:
  - name: launching ec2 instance
    ec2:
      instance_type: t2.micro
      key_name: sankar-devops
      image: ami-06b710d39da76565d
      region: us-east-2
      group: default
      count: 1
      wait: yes
      assign_public_ip: yes
      vpc_subnet_id: subnet-eb3cd196
      register: ec2 
  - name: Wait 300 seconds, but only start checking after 60 seconds
    wait_for_connection:
      delay: 60
      timeout: 180
  - debug:
       var: ec2.instances[0].public_ip    
  - name: Update Inventory File
    become: true
    lineinfile:
     path: /etc/ansible/hosts
     line: ${{ var }}
